# Generated by Django 4.0.3 on 2022-08-10 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room_module', '0013_remove_roombookingdetail_room_booking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('amount', models.IntegerField(verbose_name='تعداد روزها')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لیست رزرو',
                'verbose_name_plural': 'لیست های رزرو',
            },
        ),
        migrations.CreateModel(
            name='RoomBookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی')),
                ('room_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve_module.roombooking', verbose_name='لیست رزرو')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_module.roomnumber', verbose_name='شماره اتاق رزرو')),
            ],
            options={
                'verbose_name': 'جزئیات لیست رزرو',
                'verbose_name_plural': 'جزئیات لیست های رزرو',
            },
        ),
    ]
