# Generated by Django 4.0.3 on 2022-08-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='capacity',
            field=models.IntegerField(default=2, verbose_name='ظرفیت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombooking',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
    ]
