# Generated by Django 4.0.3 on 2022-08-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان خدمت')),
                ('short_description', models.CharField(max_length=250, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات اصلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('image', models.ImageField(upload_to='images/services', verbose_name='تصویر')),
                ('logo', models.ImageField(upload_to='images/services', verbose_name='لوگو')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=100, unique=True, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
    ]
