# Generated by Django 4.0.3 on 2022-08-02 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن ارتباط با ما')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال (نمایش در سایت)')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_module.contactus', verbose_name='والد نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'لیست ارتباط با ما',
            },
        ),
    ]
