# Generated by Django 4.0.3 on 2022-08-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0003_alter_contactus_is_read_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال (نمایش در سایت)'),
        ),
    ]
