# Generated by Django 4.0.3 on 2022-07-17 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('room_number', models.IntegerField(verbose_name='شماره اتاق')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
            ],
            options={
                'verbose_name': 'اتاق',
                'verbose_name_plural': 'اتاق ها',
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_image', models.CharField(max_length=50, verbose_name='نام عکس')),
                ('images', models.ImageField(upload_to='images/rooms', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'عکس اتاق',
                'verbose_name_plural': 'عکس های اتاق',
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField(auto_now=True, verbose_name='تاریخ شروع')),
                ('end_day', models.DateField(auto_now=True, verbose_name='تاریخ پایان')),
                ('amount', models.IntegerField(verbose_name='تعداد روزها')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room_module.room', verbose_name='اتاق رزرو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room_module.roomcategory', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room_module.roomimage', verbose_name='عکس های اتاق'),
        ),
    ]
