# Generated by Django 4.0.3 on 2022-07-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_module', '0003_remove_room_room_images_roomimage_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default='', max_length=150, verbose_name='عنوان در url'),
        ),
    ]
