# Generated by Django 4.0.3 on 2022-07-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_module', '0004_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='عنوان در url'),
        ),
    ]
