# Generated by Django 4.0.3 on 2022-07-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_module', '0005_alter_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='images/rooms', verbose_name='عکس اصلی اتاق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=150, verbose_name='عنوان در url (انگلیسی)'),
        ),
    ]
