# Generated by Django 4.0.3 on 2022-07-28 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_module', '0006_room_main_image_alter_room_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomimage',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='room',
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room_module.roomcategory', verbose_name='نام دسته بندی اتاق'),
        ),
    ]
