# Generated by Django 4.0.3 on 2022-07-28 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_module', '0007_rename_images_roomimage_image_remove_roomimage_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='room_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_module.roomcategory', verbose_name='نام دسته بندی اتاق'),
        ),
    ]
