# Generated by Django 4.0.3 on 2022-08-04 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room_module', '0008_alter_roomimage_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=150, verbose_name='عنوان در url (انگلیسی)')),
                ('main_image', models.ImageField(blank=True, upload_to='images/rooms', verbose_name='عکس اصلی اتاق')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_module.roomcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'نوع اتاق',
                'verbose_name_plural': 'انواع اتاق ها',
            },
        ),
        migrations.CreateModel(
            name='RoomNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True, verbose_name='شماره اتاق')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_module.roomtype', verbose_name='نوع اتاق')),
            ],
            options={
                'verbose_name': 'شماره اتاق',
                'verbose_name_plural': 'شماره اتاق ها',
            },
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_module.roomtype', verbose_name='اتاق رزرو'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
