# Generated by Django 4.0.3 on 2022-08-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_module', '0009_alter_roombooking_user_roomtype_roomnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombooking',
            old_name='end_day',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='roombooking',
            old_name='start_day',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_module.roomnumber', verbose_name='شماره اتاق رزرو'),
        ),
    ]
