# Generated by Django 4.0.3 on 2022-08-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_module', '0010_rename_end_day_roombooking_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roombooking',
            options={'verbose_name': 'لیست رزرو', 'verbose_name_plural': 'لیست های رزرو'},
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='room',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.CreateModel(
            name='RoomBookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی')),
                ('room_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_module.roombooking', verbose_name='لیست رزرو')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_module.roomnumber', verbose_name='شماره اتاق رزرو')),
            ],
            options={
                'verbose_name': 'جزئیات لیست رزرو',
                'verbose_name_plural': 'جزئیات لیست های رزرو',
            },
        ),
    ]
