# Generated by Django 4.0.3 on 2022-08-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_module', '0011_alter_roombooking_options_remove_roombooking_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomnumber',
            old_name='room_number',
            new_name='number',
        ),
    ]
