# Generated by Django 4.0.3 on 2022-08-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_module', '0012_rename_room_number_roomnumber_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombookingdetail',
            name='room_booking',
        ),
        migrations.RemoveField(
            model_name='roombookingdetail',
            name='room_number',
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=150, verbose_name='عنوان در url'),
        ),
        migrations.DeleteModel(
            name='RoomBooking',
        ),
        migrations.DeleteModel(
            name='RoomBookingDetail',
        ),
    ]
