# Generated by Django 4.0.3 on 2022-08-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_module', '0013_remove_roombookingdetail_room_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت نوع اتاق'),
        ),
    ]
