# Generated by Django 4.0.3 on 2022-07-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_center_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touristcenter',
            options={'verbose_name': 'مرکز گردشگری', 'verbose_name_plural': 'مراکز گردشگری'},
        ),
    ]
