# Generated by Django 4.0.3 on 2022-07-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_center_module', '0002_alter_touristcenter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristcenter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
