# Generated by Django 4.0.3 on 2022-07-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_center_module', '0003_touristcenter_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristcenter',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150, verbose_name='عنوان در url'),
        ),
    ]
