# Generated by Django 4.0.3 on 2022-07-17 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('price', models.CharField(max_length=50, verbose_name='قیمت')),
                ('day_number', models.IntegerField(verbose_name='تعداد روز های تور')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
                ('start_day', models.DateField(auto_now=True, verbose_name='روز شروع')),
                ('end_day', models.DateField(auto_now=True, verbose_name='روز پایان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='images/tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour_module.tour', verbose_name='تور رزرو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزرو تور',
                'verbose_name_plural': 'تورهای رزرو',
            },
        ),
    ]
