# Generated by Django 4.0.3 on 2022-07-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'تور', 'verbose_name_plural': 'تورها'},
        ),
    ]
