# Generated by Django 4.0.3 on 2022-07-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_module', '0002_alter_tour_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end_day',
            field=models.DateField(verbose_name='روز پایان'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_day',
            field=models.DateField(verbose_name='روز شروع'),
        ),
    ]
