# Generated by Django 4.0.3 on 2022-07-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_module', '0003_alter_tour_end_day_alter_tour_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='day_number',
            field=models.IntegerField(blank=True, verbose_name='تعداد روز های تور'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(upload_to='images/tour', verbose_name='عکس'),
        ),
    ]
