# Generated by Django 4.0.3 on 2022-07-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_module', '0004_alter_tour_day_number_alter_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='day_number',
            field=models.IntegerField(blank=True, editable=False, verbose_name='تعداد روز های تور'),
        ),
    ]
