# Generated by Django 4.0.3 on 2022-07-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_module', '0006_tour_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=150, verbose_name='عنوان در url'),
        ),
    ]
