# Generated by Django 4.0.3 on 2022-08-13 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour_module', '0007_tour_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='end_day',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='start_day',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='number',
            field=models.IntegerField(default=0, verbose_name='تعداد افراد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_module.tour', verbose_name='تور رزرو'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
