# Generated by Django 4.0.3 on 2022-08-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_module', '0008_rename_end_day_tour_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourbooking',
            options={'verbose_name': 'رزرو تور', 'verbose_name_plural': 'لیست تورهای رزرو'},
        ),
    ]
