# Generated by Django 4.0.3 on 2022-08-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_module', '0009_alter_tourbooking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
    ]
